__all__ = [
    'q1_grading_students',
    'q2_apple_and_orange',
    'q3_kangaroo',
    'q7_divisible_sum_pairs',
    'q8_migratory_birds',
    'q11_sock_merchant',
    'q12_drawing_book',
    'q15_cats_and_a_mouse',
    'q21_utopian_tree',
    'q24_strange_advertising',
    'q30_extra_long_factorials',
    'q36_repeated_string',
    'q50_chocolate_feast',
]
